### ISSUE TITLE
Gradle - 用IDEA生成可執行的jar檔

### ISSUE THREAD

**Issue by RammusXu** [RammusXu/rammusxu.github.io#30]
這邊以加入AmazionSQS的dependency為例

在使用gradle打包完jar檔後執行，發現會出現`NoClassDefFoundError`的錯誤訊息。
## Error Log

```
rammus@Rammus-MacBook-Pro.local:~/workspace/HelloWorld/build$ java -jar libs/HelloWorld-1.0.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/services/sqs/AmazonSQS
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.sqs.AmazonSQS
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

解開jar檔後發現根本沒有dependency的library，google了很久之後，才找到必須在打包的task裡面加入dependency的語法[2]。
## build.gradle

``` gradle
jar {
    manifest {
        attributes 'Main-Class': 'com.hello.aws.Main'
    }

    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}
```

`attributes 'Main-Class': 'com.hello.aws.Main'`決定jar檔的進入點(Entry Point)
`from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }`將相依的class都加入jar檔

---

編輯完build.gradle後可以在projectt根目錄下執行

``` bash
./gradlew jar
```

或是透過IDE的gradle plugin執行task:jar
- refresh
  ![refresh-gradle-project](https://cloud.githubusercontent.com/assets/4367069/17770847/862df992-6572-11e6-8793-a4b426cd7f07.png)
- run task:jar
  ![build-jar](https://cloud.githubusercontent.com/assets/4367069/17770746/f1d39c34-6571-11e6-9567-a6fde60e0016.png)
## Run

``` bash
java -jar xxxxxxx.jar
```
## Snippet

``` gradle
group 'com.hello.aws'
version '1.0'

apply plugin: 'java'
apply plugin: "io.spring.dependency-management"

sourceCompatibility = 1.5

repositories {
    mavenCentral()
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.4.RELEASE"
    }
}


dependencyManagement {
    imports {
        mavenBom 'com.amazonaws:aws-java-sdk-bom:1.10.47'
    }
}

dependencies {
    compile 'com.amazonaws:aws-java-sdk-sqs'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.hello.aws.Main'
    }

    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

```
## Reference
- [1] Creating runnable JAR with Gradle http://stackoverflow.com/questions/21721119/creating-runnable-jar-with-gradle
- [2] Gradle – Create a Jar file with dependencies https://www.mkyong.com/gradle/gradle-create-a-jar-file-with-dependencies/

**Comment by RammusXu** [comment]
tag: [gradle,intellij,java]
using-gradle-to-create-a-runnable-jar-with-dependencies-in-intellij-idea
